No stack traces printed during native compile when using an ubuntu
based builder. Need to run as root though to avoid permission issues
when the build result is written.

The integration test still dies on
NoSuchMethodError: com.caoccao.javet.interop.V8Runtime.gcPrologueCallback(II)V